const config = @import("../../config.zig");
const terminal = @import("../../terminal.zig");

pub const ResolvedKeybindings = struct {
    new_file: terminal.KeyEvent,
    open_file: terminal.KeyEvent,
    open_folder: terminal.KeyEvent,
    settings: terminal.KeyEvent,
    quit: terminal.KeyEvent,
    toggle_explorer: terminal.KeyEvent,
    toggle_terminal: terminal.KeyEvent,
    switch_focus: terminal.KeyEvent,
    close_tab: terminal.KeyEvent,
    next_tab: terminal.KeyEvent,
    previous_tab: terminal.KeyEvent,
    jump_back: terminal.KeyEvent,
    jump_forward: terminal.KeyEvent,
    dashboard_up: terminal.KeyEvent,
    dashboard_down: terminal.KeyEvent,
    dashboard_select: terminal.KeyEvent,
    explorer_up: terminal.KeyEvent,
    explorer_down: terminal.KeyEvent,
    explorer_open: terminal.KeyEvent,
    explorer_new_file: terminal.KeyEvent,
    explorer_rename: terminal.KeyEvent,
    explorer_delete: terminal.KeyEvent,
    insert_mode: terminal.KeyEvent,
    command_mode: terminal.KeyEvent,
    search_mode: terminal.KeyEvent,
    normal_mode: terminal.KeyEvent,
    insert_newline: terminal.KeyEvent,
    delete_back: terminal.KeyEvent,
    delete_word_back: terminal.KeyEvent,
    indent: terminal.KeyEvent,
    prompt_submit: terminal.KeyEvent,
    prompt_backspace: terminal.KeyEvent,
    save: terminal.KeyEvent,
    undo: terminal.KeyEvent,
    redo: terminal.KeyEvent,
    select_all: terminal.KeyEvent,
    copy: terminal.KeyEvent,
    cut: terminal.KeyEvent,
    paste: terminal.KeyEvent,
    duplicate_line: terminal.KeyEvent,
    delete_line: terminal.KeyEvent,
    add_cursor_above: terminal.KeyEvent,
    add_cursor_below: terminal.KeyEvent,
    move_up: terminal.KeyEvent,
    move_down: terminal.KeyEvent,
    move_left: terminal.KeyEvent,
    move_right: terminal.KeyEvent,
    line_start: terminal.KeyEvent,
    line_end: terminal.KeyEvent,
    word_left: terminal.KeyEvent,
    word_right: terminal.KeyEvent,
    search_next: terminal.KeyEvent,
    search_previous: terminal.KeyEvent,
    completion_auto_trigger: terminal.KeyEvent,
    completion_trigger: terminal.KeyEvent,
    completion_next: terminal.KeyEvent,
    completion_previous: terminal.KeyEvent,
    completion_accept: terminal.KeyEvent,
    completion_cancel: terminal.KeyEvent,

    pub fn init(keys: config.KeybindingsConfig) ResolvedKeybindings {
        return .{
            .new_file = terminal.parseKeyChord(keys.new_file),
            .open_file = terminal.parseKeyChord(keys.open_file),
            .open_folder = terminal.parseKeyChord(keys.open_folder),
            .settings = terminal.parseKeyChord(keys.settings),
            .quit = terminal.parseKeyChord(keys.quit),
            .toggle_explorer = terminal.parseKeyChord(keys.toggle_explorer),
            .toggle_terminal = terminal.parseKeyChord(keys.toggle_terminal),
            .switch_focus = terminal.parseKeyChord(keys.switch_focus),
            .close_tab = terminal.parseKeyChord(keys.close_tab),
            .next_tab = terminal.parseKeyChord(keys.next_tab),
            .previous_tab = terminal.parseKeyChord(keys.previous_tab),
            .jump_back = terminal.parseKeyChord(keys.jump_back),
            .jump_forward = terminal.parseKeyChord(keys.jump_forward),
            .dashboard_up = terminal.parseKeyChord(keys.dashboard_up),
            .dashboard_down = terminal.parseKeyChord(keys.dashboard_down),
            .dashboard_select = terminal.parseKeyChord(keys.dashboard_select),
            .explorer_up = terminal.parseKeyChord(keys.explorer_up),
            .explorer_down = terminal.parseKeyChord(keys.explorer_down),
            .explorer_open = terminal.parseKeyChord(keys.explorer_open),
            .explorer_new_file = terminal.parseKeyChord(keys.explorer_new_file),
            .explorer_rename = terminal.parseKeyChord(keys.explorer_rename),
            .explorer_delete = terminal.parseKeyChord(keys.explorer_delete),
            .insert_mode = terminal.parseKeyChord(keys.insert_mode),
            .command_mode = terminal.parseKeyChord(keys.command_mode),
            .search_mode = terminal.parseKeyChord(keys.search_mode),
            .normal_mode = terminal.parseKeyChord(keys.normal_mode),
            .insert_newline = terminal.parseKeyChord(keys.insert_newline),
            .delete_back = terminal.parseKeyChord(keys.delete_back),
            .delete_word_back = terminal.parseKeyChord(keys.delete_word_back),
            .indent = terminal.parseKeyChord(keys.indent),
            .prompt_submit = terminal.parseKeyChord(keys.prompt_submit),
            .prompt_backspace = terminal.parseKeyChord(keys.prompt_backspace),
            .save = terminal.parseKeyChord(keys.save),
            .undo = terminal.parseKeyChord(keys.undo),
            .redo = terminal.parseKeyChord(keys.redo),
            .select_all = terminal.parseKeyChord(keys.select_all),
            .copy = terminal.parseKeyChord(keys.copy),
            .cut = terminal.parseKeyChord(keys.cut),
            .paste = terminal.parseKeyChord(keys.paste),
            .duplicate_line = terminal.parseKeyChord(keys.duplicate_line),
            .delete_line = terminal.parseKeyChord(keys.delete_line),
            .add_cursor_above = terminal.parseKeyChord(keys.add_cursor_above),
            .add_cursor_below = terminal.parseKeyChord(keys.add_cursor_below),
            .move_up = terminal.parseKeyChord(keys.move_up),
            .move_down = terminal.parseKeyChord(keys.move_down),
            .move_left = terminal.parseKeyChord(keys.move_left),
            .move_right = terminal.parseKeyChord(keys.move_right),
            .line_start = terminal.parseKeyChord(keys.line_start),
            .line_end = terminal.parseKeyChord(keys.line_end),
            .word_left = terminal.parseKeyChord(keys.word_left),
            .word_right = terminal.parseKeyChord(keys.word_right),
            .search_next = terminal.parseKeyChord(keys.search_next),
            .search_previous = terminal.parseKeyChord(keys.search_previous),
            .completion_auto_trigger = terminal.parseKeyChord(keys.completion_auto_trigger),
            .completion_trigger = terminal.parseKeyChord(keys.completion_trigger),
            .completion_next = terminal.parseKeyChord(keys.completion_next),
            .completion_previous = terminal.parseKeyChord(keys.completion_previous),
            .completion_accept = terminal.parseKeyChord(keys.completion_accept),
            .completion_cancel = terminal.parseKeyChord(keys.completion_cancel),
        };
    }
};
