# flamingo configuration

[storage]
data_dir = "./data"

[keybindings]
new_file = "ctrl+n"
open_file = "ctrl+o"
settings = "ctrl+p"
toggle_explorer = "ctrl+e"
switch_focus = "ctrl+w"

[explorer]
width_percentage = 20
